#!/usr/bin/env bash
# Marabunta - Licensed under the MIT License.
#
# setup-signing.sh — Generate a release keystore for Marabunta Worker
#
# This script creates a release signing keystore for building the
# Play Store AAB (Android App Bundle). Run it once before your first
# release build.
#
# Usage:
#   ./setup-signing.sh
#
# Environment variables (optional):
#   KEYSTORE_PATH     — Path to the keystore file (default: release.keystore)
#   STORE_PASS        — Keystore password (prompted if not set)
#   KEY_PASS          — Key password (prompted if not set)
#   KEY_ALIAS         — Key alias (default: marabunta)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

KEYSTORE_PATH="${KEYSTORE_PATH:-release.keystore}"
KEY_ALIAS="${KEY_ALIAS:-marabunta}"

# ── Check for keytool ─────────────────────────────────────────────
if ! command -v keytool &> /dev/null; then
    echo "ERROR: 'keytool' not found."
    echo "       Install a JDK (e.g., openjdk-17-jdk) or ensure JAVA_HOME/bin is on your PATH."
    exit 1
fi

# ── Check if keystore already exists ──────────────────────────────
if [ -f "$KEYSTORE_PATH" ]; then
    echo "Keystore already exists at: $KEYSTORE_PATH"
    echo ""
    echo "To regenerate, remove it first:"
    echo "  rm $KEYSTORE_PATH"
    echo "  ./setup-signing.sh"
    echo ""
    echo "WARNING: If you lose your release keystore, you cannot update"
    echo "         your app on Google Play. Back it up securely."
    exit 0
fi

# ── Prompt for passwords if not provided via environment ──────────
if [ -z "${STORE_PASS:-}" ]; then
    echo -n "Enter keystore password (min 6 characters): "
    read -rs STORE_PASS
    echo ""
    if [ ${#STORE_PASS} -lt 6 ]; then
        echo "ERROR: Password must be at least 6 characters."
        exit 1
    fi
    echo -n "Confirm keystore password: "
    read -rs STORE_PASS_CONFIRM
    echo ""
    if [ "$STORE_PASS" != "$STORE_PASS_CONFIRM" ]; then
        echo "ERROR: Passwords do not match."
        exit 1
    fi
fi

if [ -z "${KEY_PASS:-}" ]; then
    KEY_PASS="$STORE_PASS"
    echo "Using the same password for the key (recommended for Android signing)."
fi

# ── Generate the keystore ─────────────────────────────────────────
echo ""
echo "Generating release keystore..."
echo ""

keytool -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$KEY_ALIAS" \
    -keyalg EC \
    -keysize 256 \
    -validity 10000 \
    -storepass "$STORE_PASS" \
    -keypass "$KEY_PASS" \
    -dname "CN=Marabunta Swarm, O=Marabunta, L=Earth"

echo ""
echo "Keystore generated successfully: $KEYSTORE_PATH"
echo ""

# ── Create local.properties with signing config ──────────────────
LOCAL_PROPS="local.properties"

if [ -f "$LOCAL_PROPS" ]; then
    # Check if signing config already exists
    if grep -q "signing.storeFile" "$LOCAL_PROPS" 2>/dev/null; then
        echo "Signing configuration already present in $LOCAL_PROPS"
    else
        echo "" >> "$LOCAL_PROPS"
        echo "# Release signing configuration (generated by setup-signing.sh)" >> "$LOCAL_PROPS"
        echo "signing.storeFile=$KEYSTORE_PATH" >> "$LOCAL_PROPS"
        echo "signing.storePassword=$STORE_PASS" >> "$LOCAL_PROPS"
        echo "signing.keyAlias=$KEY_ALIAS" >> "$LOCAL_PROPS"
        echo "signing.keyPassword=$KEY_PASS" >> "$LOCAL_PROPS"
        echo "Updated $LOCAL_PROPS with signing configuration."
    fi
else
    # Create local.properties from the example template
    if [ -f "local.properties.example" ]; then
        cp local.properties.example "$LOCAL_PROPS"
    else
        echo "# Auto-generated by setup-signing.sh" > "$LOCAL_PROPS"
    fi
    # Append signing config
    echo "" >> "$LOCAL_PROPS"
    echo "# Release signing configuration (generated by setup-signing.sh)" >> "$LOCAL_PROPS"
    echo "signing.storeFile=$KEYSTORE_PATH" >> "$LOCAL_PROPS"
    echo "signing.storePassword=$STORE_PASS" >> "$LOCAL_PROPS"
    echo "signing.keyAlias=$KEY_ALIAS" >> "$LOCAL_PROPS"
    echo "signing.keyPassword=$KEY_PASS" >> "$LOCAL_PROPS"
    echo "Created $LOCAL_PROPS with signing configuration."
fi

# ── Print next steps ─────────────────────────────────────────────
echo ""
echo "================================================================"
echo "  IMPORTANT: Back up your keystore and passwords securely!"
echo ""
echo "  If you lose the release keystore, you will NOT be able to"
echo "  push updates to Google Play for the same package name."
echo "================================================================"
echo ""
echo "Next steps to build the release AAB:"
echo ""
echo "  1. Ensure your Android SDK is configured:"
echo "     Check android/local.properties has the correct sdk.dir"
echo ""
echo "  2. Build the native Rust libraries:"
echo "     ./scripts/android-build.sh"
echo ""
echo "  3. Build the release AAB (Android App Bundle):"
echo "     cd android && ./gradlew bundleRelease"
echo ""
echo "  4. The signed AAB will be at:"
echo "     android/app/build/outputs/bundle/release/app-release.aab"
echo ""
echo "  5. Upload the AAB to Google Play Console:"
echo "     https://play.google.com/console"
echo ""
echo "Alternative: Build using environment variables (CI/CD):"
echo "  export KEYSTORE_PATH=$KEYSTORE_PATH"
echo "  export KEYSTORE_PASSWORD=<your-password>"
echo "  export KEY_ALIAS=$KEY_ALIAS"
echo "  export KEY_PASSWORD=<your-password>"
echo "  cd android && ./gradlew bundleRelease"
echo ""
