// Marabunta - Licensed under the MIT License.
//! Configuration constants for the Marabunta Swarm.
//!
//! All timing, sizing, and threshold values live here. These are compile-time
//! defaults; runtime overrides are supported via `SwarmConfig`.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::time::Duration;

// Build-time compliance profile (generated by build.rs).
// Contains COMPLIANCE_PROFILE_NAME, COMPLIANCE_PROFILE_VERSION,
// COMPLIANCE_PROFILE_DESCRIPTION, and compliance_overrides().
include!(concat!(env!("OUT_DIR"), "/compliance_generated.rs"));

// ============================================================================
// Gossip timing
// ============================================================================

/// How often each node sends gossip messages.
pub const GOSSIP_INTERVAL: Duration = Duration::from_millis(1000);

/// Number of random peers to gossip with per round.
pub const GOSSIP_FANOUT: usize = 3;

/// Minimum fanout regardless of cluster size (floor for dynamic fanout).
pub const GOSSIP_MIN_FANOUT: usize = 3;

/// Jitter range for gossip interval (±percentage). Prevents thundering herd.
pub const GOSSIP_JITTER_PERCENT: u32 = 20;

/// Fraction of gossip fanout directed to same-region peers (0.0 = all random, 1.0 = all same-region).
///
/// When a node has a `geo_region` set, peer selection is biased so that
/// approximately this fraction of gossip targets are in the same region,
/// reducing WAN bandwidth waste in geographically distributed swarms.
/// If the node has no region set, or there are insufficient same-region peers,
/// the remainder is filled from cross-region peers (and vice versa).
pub const GOSSIP_SAME_REGION_RATIO: f32 = 0.7;

// ============================================================================
// Failure detection
// ============================================================================

/// After this silence, a node is marked Suspect.
pub const SUSPECT_THRESHOLD: Duration = Duration::from_secs(10);

/// After this silence, a node is marked Dead and its work is reassigned.
pub const DEAD_THRESHOLD: Duration = Duration::from_secs(30);

/// After this silence, a node is evicted from the knowledge store entirely.
pub const NODE_TIMEOUT: Duration = Duration::from_secs(120);

/// How often the failure detector runs its sweep.
pub const FAILURE_CHECK_INTERVAL: Duration = Duration::from_secs(2);

// ============================================================================
// DNS resolution
// ============================================================================

/// Time-to-live for cached DNS resolution results.
pub const DNS_CACHE_TTL: Duration = Duration::from_secs(60);

// ============================================================================
// Split-brain protection
// ============================================================================

/// Witness reports older than this are discarded during quorum evaluation.
pub const WITNESS_DECAY_SECS: u64 = 60;

/// Fraction of active peers that must agree a node is unreachable before
/// it can be declared dead. Prevents unilateral death declarations during
/// transient network partitions.
pub const QUORUM_FRACTION: f32 = 0.5;

/// Number of consecutive healthy gossip rounds (reachable_fraction >= QUORUM_FRACTION)
/// required before a partition is considered healed and the node resumes normal
/// work claiming.
pub const PARTITION_RECOVERY_ROUNDS: u32 = 2;

/// Maximum number of witness reports to include in a single gossip message.
pub const MAX_WITNESS_REPORTS_PER_MESSAGE: usize = 20;

// ============================================================================
// Work distribution
// ============================================================================

/// Maximum load before a node stops accepting new chunks.
pub const MAX_LOAD_THRESHOLD: f32 = 0.8;

/// How often the work loop checks for available chunks to claim.
pub const WORK_CHECK_INTERVAL: Duration = Duration::from_millis(500);

/// Default timeout for chunk execution.
pub const CHUNK_TIMEOUT: Duration = Duration::from_secs(300);

/// Maximum attempts before a chunk is marked permanently failed.
pub const MAX_CHUNK_ATTEMPTS: u32 = 3;

/// Maximum number of chunks a single node can execute concurrently.
pub const MAX_CONCURRENT_CHUNKS: usize = 4;

/// How long to wait after a conflict-resolution loss before reclaiming work.
pub const CONFLICT_BACKOFF: Duration = Duration::from_millis(200);

// ============================================================================
// Trait evaluation thresholds
// ============================================================================

/// Minimum CPU availability fraction to claim `can_execute`.
pub const THRESHOLD_EXECUTE_CPU: f32 = 0.1;

/// Minimum available RAM (MB) to claim `can_aggregate`.
pub const THRESHOLD_AGGREGATE_RAM_MB: u64 = 512;

/// Maximum load to claim `can_forward`.
pub const THRESHOLD_FORWARD_LOAD: f32 = 0.5;

/// Minimum available disk (MB) to claim `can_store_state`.
pub const THRESHOLD_STORE_DISK_MB: u64 = 1024;

/// Minimum bandwidth (Mbps) to claim `can_relay`.
pub const THRESHOLD_RELAY_BANDWIDTH_MBPS: f32 = 10.0;

/// How often trait evaluation runs.
pub const TRAIT_EVAL_INTERVAL: Duration = Duration::from_secs(5);

// ============================================================================
// Message size limits
// ============================================================================

/// Maximum NodeInfo entries per gossip message.
pub const MAX_NODES_PER_MESSAGE: usize = 50;

/// Maximum SwarmJobInfo entries per gossip message.
pub const MAX_JOBS_PER_MESSAGE: usize = 20;

/// Maximum Assignment entries per gossip message.
pub const MAX_ASSIGNMENTS_PER_MESSAGE: usize = 100;

/// Maximum wire size of a single SwarmMessage (16 MB).
pub const MAX_MESSAGE_SIZE: usize = 16 * 1024 * 1024;

/// Maximum ShardMapEntry entries per gossip message.
pub const MAX_SHARD_ENTRIES_PER_MESSAGE: usize = 50;

/// Maximum NodeProfile entries per gossip message.
pub const MAX_PROFILES_PER_MESSAGE: usize = 30;

/// Maximum Collective entries per gossip message.
pub const MAX_COLLECTIVES_PER_MESSAGE: usize = 15;

/// Maximum ReputationRecord entries per gossip message.
pub const MAX_REPUTATION_PER_MESSAGE: usize = 50;

/// Maximum MarketplacePosting entries per gossip message.
pub const MAX_POSTINGS_PER_MESSAGE: usize = 40;

// ============================================================================
// Transport
// ============================================================================

/// Timeout for establishing a TCP connection to a peer.
pub const TRANSPORT_CONNECT_TIMEOUT: Duration = Duration::from_secs(5);

/// Timeout for reading a complete message frame.
pub const TRANSPORT_READ_TIMEOUT: Duration = Duration::from_secs(10);

/// Maximum idle time before closing an unused connection.
pub const CONNECTION_IDLE_TIMEOUT: Duration = Duration::from_secs(60);

/// Maximum number of concurrent outbound connections.


/// TCP listen backlog.
pub const LISTEN_BACKLOG: u32 = 512;

// ============================================================================
// Bootstrap
// ============================================================================

/// Delay between bootstrap retry attempts.
pub const BOOTSTRAP_RETRY_INTERVAL: Duration = Duration::from_secs(5);

/// Maximum number of bootstrap attempts before giving up.
pub const BOOTSTRAP_MAX_RETRIES: u32 = 12;

/// How many peers to request from a bootstrap server.
pub const BOOTSTRAP_PEER_REQUEST_COUNT: usize = 100;

// ============================================================================
// Knowledge store limits
// ============================================================================

/// Maximum number of nodes tracked in the knowledge store.
/// Prevents unbounded memory growth in very large swarms.
pub const MAX_KNOWN_NODES: usize = 10_000;

/// Maximum number of active jobs tracked.
pub const MAX_KNOWN_JOBS: usize = 5_000;

/// Maximum number of assignments tracked.
pub const MAX_KNOWN_ASSIGNMENTS: usize = 5_000_000;

/// How often the knowledge store prunes stale entries.
pub const KNOWLEDGE_PRUNE_INTERVAL: Duration = Duration::from_secs(15);

// ============================================================================
// Organic Swarm: Profile
// ============================================================================

/// How often each node broadcasts its profile to the swarm.
pub const PROFILE_BROADCAST_INTERVAL: Duration = Duration::from_secs(30);

/// A profile is considered stale after this age.
pub const PROFILE_STALE_AGE: Duration = Duration::from_secs(300); // 5 min

/// Maximum number of specializations a node can declare.
pub const MAX_SPECIALIZATIONS: usize = 10;

// ============================================================================
// Organic Swarm: Collectives
// ============================================================================

/// How often collective quality is re-evaluated.
pub const COLLECTIVE_EVAL_INTERVAL: Duration = Duration::from_secs(10);

/// Timeout for a collective formation proposal.
pub const COLLECTIVE_PROPOSAL_TIMEOUT: Duration = Duration::from_secs(30);

/// Minimum number of members to form a collective.
pub const COLLECTIVE_MIN_MEMBERS: usize = 2;

/// Maximum number of members in a collective.
pub const COLLECTIVE_MAX_MEMBERS: usize = 12;

/// Maximum number of collectives a single node may join.
pub const MAX_COLLECTIVES_PER_NODE: usize = 3;

/// Collective quality below this threshold triggers dissolution.
pub const COLLECTIVE_MIN_QUALITY: f32 = 0.3;

// ============================================================================
// Organic Swarm: Marketplace
// ============================================================================

/// How long to keep the bidding window open for a posting.
pub const BID_WINDOW: Duration = Duration::from_secs(5);

/// Postings expire after this duration if not awarded.
pub const POSTING_EXPIRY: Duration = Duration::from_secs(300); // 5 min

/// How often nodes auto-bid on suitable postings.
pub const AUTO_BID_INTERVAL: Duration = Duration::from_secs(2);

/// How often the marketplace runs its award cycle.
pub const AWARD_CYCLE_INTERVAL: Duration = Duration::from_secs(5);

/// How often marketplace maintenance (expiry cleanup, etc.) runs.
pub const MARKETPLACE_MAINTENANCE_INTERVAL: Duration = Duration::from_secs(30);

/// Minimum capability match score to be eligible for a posting.
pub const MIN_CAPABILITY_MATCH: f32 = 0.5;

/// Maximum number of bids accepted per posting.
pub const MAX_BIDS_PER_POSTING: usize = 50;

// ============================================================================
// Organic Swarm: Reputation
// ============================================================================

/// Number of recent jobs to consider in rolling reputation window.
pub const ROLLING_WINDOW_SIZE: usize = 50;

/// Nodes with fewer than this many completed jobs are considered newcomers.
pub const NEWCOMER_THRESHOLD: u64 = 50;

/// Speed ratio threshold for earning the LightningSpeed badge.
pub const LIGHTNING_SPEED_EARN: f32 = 0.9;

/// Speed ratio threshold for shedding the LightningSpeed badge.
pub const LIGHTNING_SPEED_SHED: f32 = 1.2;

/// Minimum completed jobs to qualify for the Reliable badge.
pub const RELIABLE_MIN_JOBS: u64 = 100;

/// Maximum failure rate to qualify for the Reliable badge.
pub const RELIABLE_MAX_FAILURE_RATE: f32 = 0.02;

/// Failure rate above which the Reliable badge is shed.
pub const RELIABLE_SHED_RATE: f32 = 0.95;

/// Minimum completed jobs to qualify for the Trusted badge.
pub const TRUSTED_MIN_JOBS: u64 = 200;

/// Minimum large-job completions for the HeavyLifter badge.
pub const HEAVY_LIFTER_MIN_LARGE: u64 = 20;

/// Minimum success rate for the HeavyLifter badge.
pub const HEAVY_LIFTER_SUCCESS_RATE: f32 = 0.95;

/// Minimum months of uptime for the Veteran badge.
pub const VETERAN_MIN_MONTHS: f32 = 6.0;

/// Minimum completed jobs for the Veteran badge.
pub const VETERAN_MIN_JOBS: u64 = 500;

/// Minimum distinct badges for the Veteran badge.
pub const VETERAN_MIN_BADGES: usize = 3;

/// Reputation data is considered stale after this age.
pub const REPUTATION_STALE_AGE: Duration = Duration::from_secs(3600); // 1 hour

// ============================================================================
// Organic Swarm: Policy
// ============================================================================

/// How often policy maintenance (violation expiry, etc.) runs.
pub const POLICY_MAINTENANCE_INTERVAL: Duration = Duration::from_secs(60);

/// Maximum age of a violation before it is pruned.
pub const VIOLATION_MAX_AGE: Duration = Duration::from_secs(86400); // 24 hours

/// Default rate limit (requests per hour) for policy enforcement.
pub const RATE_LIMIT_DEFAULT_PER_HOUR: u32 = 100;

// ============================================================================
// Data Residency
// ============================================================================

/// Maximum number of entries in the residency audit log before FIFO eviction.
pub const RESIDENCY_AUDIT_MAX_ENTRIES: usize = 10_000;

/// Whether residency audit logging is enabled by default.
pub const RESIDENCY_AUDIT_ENABLED: bool = true;

// ============================================================================
// Organic Swarm: Scoring Weights
// ============================================================================

/// Weight of speed in composite bid scoring.
pub const SCORING_WEIGHT_SPEED: f64 = 0.2;

/// Weight of reputation in composite bid scoring.
pub const SCORING_WEIGHT_REPUTATION: f64 = 0.3;

/// Weight of capability match in composite bid scoring.
pub const SCORING_WEIGHT_CAPABILITY: f64 = 0.3;

/// Weight for energy cost in marketplace scoring (lower cost = higher score).
pub const SCORING_WEIGHT_ENERGY: f64 = 0.2;

// ============================================================================
// Latency probing
// ============================================================================

/// Interval between latency probe rounds.
pub const LATENCY_PROBE_INTERVAL: Duration = Duration::from_secs(30);

/// Number of peers to probe per round.
pub const LATENCY_PROBE_PEERS: usize = 5;

/// EWMA smoothing factor (0.0 = ignore new, 1.0 = ignore old).
/// A value of 0.3 means new measurements are weighted 30%, giving a
/// smooth moving average that reacts to trends without jittering on
/// individual outliers.
pub const LATENCY_EWMA_ALPHA: f32 = 0.3;

/// Timeout for an individual probe connection attempt.
pub const LATENCY_PROBE_TIMEOUT: Duration = Duration::from_secs(5);

// ============================================================================
// Production: API Server (Phase 1)
// ============================================================================

/// Default HTTP API port.
pub const API_DEFAULT_PORT: u16 = 8080;

/// Maximum request body size for API (32 MB).
pub const API_MAX_BODY_SIZE: usize = 32 * 1024 * 1024;

/// Maximum blob upload size (1 GB).
pub const API_MAX_BLOB_SIZE: u64 = 1024 * 1024 * 1024;

// ============================================================================
// Production: Authentication (Phase 2)
// ============================================================================

/// Maximum staleness of a signed gossip message before rejection.
pub const AUTH_MAX_MESSAGE_AGE: Duration = Duration::from_secs(300); // 5 min

/// Default API token expiry (30 days).
pub const AUTH_TOKEN_DEFAULT_EXPIRY: Duration = Duration::from_secs(30 * 86400);

// ============================================================================
// Production: Sandbox (Phase 3)
// ============================================================================

/// Default memory limit for sandboxed execution (512 MB).


/// Default CPU shares (cgroup cpu.weight).
pub const SANDBOX_DEFAULT_CPU_SHARES: u32 = 100;

/// Default PID limit to prevent fork bombs.
pub const SANDBOX_DEFAULT_MAX_PIDS: u32 = 64;

/// Default disk limit for job tmpfs (256 MB).


/// Base directory for sandboxed job execution.
pub const SANDBOX_JOBS_DIR: &str = "/tmp/marabunta/jobs";

// ============================================================================
// Production: Blob Store (Phase 4)
// ============================================================================

/// Default maximum blob storage size (10 GB).


/// Maximum blobs gossipped per message.
pub const MAX_BLOBS_PER_MESSAGE: usize = 100;

/// Blob transfer chunk size (64 KB).
pub const BLOB_TRANSFER_CHUNK_SIZE: usize = 64 * 1024;

// ============================================================================
// Production: Software Discovery (Phase 5)
// ============================================================================

/// How often to re-probe installed software.
pub const DISCOVERY_INTERVAL: Duration = Duration::from_secs(3600); // 1 hour

/// Timeout for probing a single binary.
pub const DISCOVERY_PROBE_TIMEOUT: Duration = Duration::from_secs(5);

/// Maximum software entries per gossip message.
pub const MAX_SOFTWARE_PER_MESSAGE: usize = 50;

// ============================================================================
// Production: Energy (Phase 7)
// ============================================================================

/// Default power estimate: ARM core (watts, idle/load).
pub const POWER_HEURISTIC_ARM_IDLE: f64 = 1.0;
pub const POWER_HEURISTIC_ARM_LOAD: f64 = 2.5;

/// Default power estimate: x86 core (watts, idle/load).
pub const POWER_HEURISTIC_X86_IDLE: f64 = 5.0;
pub const POWER_HEURISTIC_X86_LOAD: f64 = 15.0;

/// Default energy price (USD/kWh) when no schedule is loaded.
pub const ENERGY_DEFAULT_PRICE: f64 = 0.12;

// ============================================================================
// Production: NAT Relay (Phase 8)
// ============================================================================

/// Timeout for STUN probe requests.
pub const STUN_PROBE_TIMEOUT: Duration = Duration::from_secs(5);

/// Timeout for hole-punching attempts before falling back to relay.
pub const HOLE_PUNCH_TIMEOUT: Duration = Duration::from_secs(5);

/// Maximum relay sessions per relay node.
pub const RELAY_MAX_SESSIONS: usize = 256;

/// Maximum bandwidth per relay session (1 MB/s).
pub const RELAY_MAX_BANDWIDTH: u64 = 1024 * 1024;

// ============================================================================
// Production: Checkpointing (Phase 9)
// ============================================================================

/// Default checkpoint interval for long-running chunks.
pub const CHECKPOINT_INTERVAL: Duration = Duration::from_secs(60);

/// Env var name set for scripts that support checkpointing.
pub const CHECKPOINT_DIR_ENV: &str = "MARABUNTA_CHECKPOINT_DIR";

/// Env var set to "1" when resuming from a checkpoint.
pub const CHECKPOINT_RESUME_ENV: &str = "MARABUNTA_RESUME";

// ============================================================================
// Production: Aggregation (Phase 10)
// ============================================================================

/// Maximum reduce script execution time.
pub const AGGREGATOR_REDUCE_TIMEOUT: Duration = Duration::from_secs(600);

// ============================================================================
// Production: Auto-Update (Phase 11)
// ============================================================================

/// How often to check for updates (default: 6 hours).
pub const UPDATE_CHECK_INTERVAL: Duration = Duration::from_secs(6 * 3600);

/// Maximum time allowed for downloading an update binary.
pub const UPDATE_DOWNLOAD_TIMEOUT: Duration = Duration::from_secs(300);

/// How long to wait after a successful update before running the health check.
pub const UPDATE_HEALTH_CHECK_DELAY: Duration = Duration::from_secs(60);

// ============================================================================
// Management Layer
// ============================================================================

/// How often the psyche calculator recomputes facets.
pub const PSYCHE_COMPUTE_INTERVAL_SECS: u64 = 10;

/// EventBus ring buffer capacity.
pub const EVENT_BUS_BUFFER_SIZE: usize = 10_000;

/// Maximum recent events kept for query.
pub const EVENT_RECENT_MAX: usize = 10_000;

/// How often alert rules are evaluated.
pub const ALERT_EVAL_INTERVAL_SECS: u64 = 10;

/// How often metrics are updated.
pub const METRICS_UPDATE_INTERVAL_SECS: u64 = 15;

/// How often SLA compliance is checked.
pub const SLA_CHECK_INTERVAL_SECS: u64 = 30;

/// How often capacity samples are collected.
pub const CAPACITY_SAMPLE_INTERVAL_SECS: u64 = 30;

/// How often fleet state is checked (drain progress, update progress).
pub const FLEET_CHECK_INTERVAL_SECS: u64 = 5;

/// How often health probes are executed.
pub const HEALTHCHECK_INTERVAL_SECS: u64 = 10;

/// How often sovereignty heartbeats are sent.
pub const SOVEREIGNTY_HEARTBEAT_INTERVAL_SECS: u64 = 30;

/// Remote swarm considered stale after this many seconds without heartbeat.
pub const SOVEREIGNTY_STALE_THRESHOLD_SECS: u64 = 120;

/// Remote swarm considered unreachable after this many seconds.
pub const SOVEREIGNTY_UNREACHABLE_THRESHOLD_SECS: u64 = 300;

/// Maximum crossing log entries per membrane.
pub const MEMBRANE_CROSSING_LOG_MAX: usize = 100_000;

/// Maximum audit log entries before FIFO eviction.
pub const AUDIT_LOG_MAX_ENTRIES: usize = 1_000_000;

/// Maximum psyche history snapshots retained.
pub const PSYCHE_HISTORY_MAX: usize = 8640;

/// Maximum capacity history samples retained.
pub const CAPACITY_HISTORY_MAX: usize = 86400;

/// Maximum rolling update history entries.
pub const FLEET_UPDATE_HISTORY_MAX: usize = 10;

/// Health check circuit breaker: failures before opening.
pub const CIRCUIT_BREAKER_THRESHOLD: u32 = 5;

/// Health check circuit breaker: seconds in half-open before retry.
pub const CIRCUIT_BREAKER_HALF_OPEN_SECS: u64 = 60;

/// Maximum concurrent health probes.
pub const MAX_CONCURRENT_HEALTH_PROBES: usize = 50;

// ============================================================================
// Hardware-class-aware trait thresholds
// ============================================================================

use super::traits::HardwareClass;

/// Per-hardware-class thresholds for trait evaluation and concurrency limits.
///
/// Weaker nodes get more lenient thresholds so they can still contribute
/// to the swarm instead of constantly shedding all traits.
pub struct HardwareClassThresholds {
    /// Maximum load at which a node may still claim `CanExecute`.
    pub max_execute_load: f32,
    /// Minimum available RAM (MB) to claim `CanAggregate`.
    pub min_aggregate_ram_mb: u64,
    /// Minimum available disk (MB) to claim `CanStoreState`.
    pub min_store_state_disk_mb: u64,
    /// Maximum number of chunks a single node can execute concurrently.
    pub max_concurrent_chunks: usize,
    /// Maximum load at which a node may still claim `CanStoreState`.
    pub max_store_state_load: f32,
    /// Maximum load at which a node may still claim `CanAggregate`.
    pub max_aggregate_load: f32,
}

/// Thresholds for Minimal-class hardware (< 2 cores or < 2 GB RAM).
///
/// Very lenient: these nodes are old phones, Raspberry Pi Zeros, etc.
/// They should still contribute with a single chunk at a time.
pub const THRESHOLDS_MINIMAL: HardwareClassThresholds = HardwareClassThresholds {
    max_execute_load: 0.95,
    min_aggregate_ram_mb: 128,
    min_store_state_disk_mb: 256,
    max_concurrent_chunks: 1,
    max_store_state_load: 0.8,
    max_aggregate_load: 0.9,
};

/// Thresholds for Light-class hardware (2-4 cores, 2-4 GB RAM).
///
/// Old laptops and budget phones. Slightly more capable than Minimal.
pub const THRESHOLDS_LIGHT: HardwareClassThresholds = HardwareClassThresholds {
    max_execute_load: 0.90,
    min_aggregate_ram_mb: 256,
    min_store_state_disk_mb: 512,
    max_concurrent_chunks: 2,
    max_store_state_load: 0.7,
    max_aggregate_load: 0.8,
};

/// Thresholds for Standard-class hardware (4-8 cores, 4-16 GB RAM).
///
/// Typical desktops and laptops. These match the original hardcoded defaults.
pub const THRESHOLDS_STANDARD: HardwareClassThresholds = HardwareClassThresholds {
    max_execute_load: 0.80,
    min_aggregate_ram_mb: 512,
    min_store_state_disk_mb: 1024,
    max_concurrent_chunks: 4,
    max_store_state_load: 0.6,
    max_aggregate_load: 0.7,
};

/// Thresholds for Heavy-class hardware (8+ cores, 16+ GB RAM).
///
/// Workstations and servers. Same thresholds as Standard but higher concurrency.
pub const THRESHOLDS_HEAVY: HardwareClassThresholds = HardwareClassThresholds {
    max_execute_load: 0.80,
    min_aggregate_ram_mb: 512,
    min_store_state_disk_mb: 1024,
    max_concurrent_chunks: 8,
    max_store_state_load: 0.6,
    max_aggregate_load: 0.7,
};

/// Look up the thresholds for a given hardware class.
pub fn thresholds_for_class(class: HardwareClass) -> &'static HardwareClassThresholds {
    match class {
        HardwareClass::Minimal => &THRESHOLDS_MINIMAL,
        HardwareClass::Light => &THRESHOLDS_LIGHT,
        HardwareClass::Standard => &THRESHOLDS_STANDARD,
        HardwareClass::Heavy => &THRESHOLDS_HEAVY,
    }
}

// ============================================================================
// Bounded pending chunk queue
// ============================================================================

/// Maximum number of pending chunks in the queue. Prevents OOM on low-memory nodes.
pub const MAX_PENDING_CHUNKS: usize = 5_000_000;

/// Warning threshold as fraction of max capacity.
pub const PENDING_CHUNKS_WARN_THRESHOLD: f32 = 0.8;

// ============================================================================
// Sub-configuration structs (promoted from constants)
// ============================================================================

/// Admission subsystem configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdmissionConfig {
    #[serde(default = "default_jury_min_size")]
    pub jury_min_size: usize,
    #[serde(default = "default_jury_max_size")]
    pub jury_max_size: usize,
    #[serde(default = "default_probation_min_tasks")]
    pub probation_min_tasks: u32,
    #[serde(default = "default_probation_max_tasks")]
    pub probation_max_tasks: u32,
    #[serde(default = "default_admission_test_timeout", with = "humantime_serde")]
    pub test_timeout: Duration,
    #[serde(default = "default_admission_verdict_timeout", with = "humantime_serde")]
    pub verdict_timeout: Duration,
    #[serde(default = "default_admission_failure_threshold")]
    pub failure_threshold: f32,
    #[serde(default = "default_juror_penalty")]
    pub juror_penalty: f32,
    #[serde(default = "default_juror_bonus")]
    pub juror_bonus: f32,
    #[serde(default = "default_admission_check_interval", with = "humantime_serde")]
    pub check_interval: Duration,
    #[serde(default = "default_graduation_success_rate")]
    pub graduation_success_rate: f32,
    #[serde(default = "default_rate_limit_max_requests")]
    pub rate_limit_max_requests: u32,
    #[serde(default = "default_rate_limit_window", with = "humantime_serde")]
    pub rate_limit_window: Duration,
    #[serde(default = "default_nonce_cache_size")]
    pub nonce_cache_size: usize,
    #[serde(default = "default_cpu_hash_iterations")]
    pub cpu_hash_iterations_per_core: u64,
}

impl Default for AdmissionConfig {
    fn default() -> Self {
        Self {
            jury_min_size: super::admission::JURY_MIN_SIZE,
            jury_max_size: super::admission::JURY_MAX_SIZE,
            probation_min_tasks: super::admission::PROBATION_MIN_TASKS,
            probation_max_tasks: super::admission::PROBATION_MAX_TASKS,
            test_timeout: super::admission::TEST_TIMEOUT,
            verdict_timeout: super::admission::VERDICT_TIMEOUT,
            failure_threshold: super::admission::FAILURE_THRESHOLD,
            juror_penalty: super::admission::JUROR_PENALTY,
            juror_bonus: super::admission::JUROR_BONUS,
            check_interval: super::admission::ADMISSION_CHECK_INTERVAL,
            graduation_success_rate: super::admission::GRADUATION_SUCCESS_RATE,
            rate_limit_max_requests: super::admission::RATE_LIMIT_MAX_REQUESTS,
            rate_limit_window: super::admission::RATE_LIMIT_WINDOW,
            nonce_cache_size: super::admission::NONCE_CACHE_SIZE,
            cpu_hash_iterations_per_core: super::admission::CPU_HASH_ITERATIONS_PER_CORE,
        }
    }
}

fn default_jury_min_size() -> usize { super::admission::JURY_MIN_SIZE }
fn default_jury_max_size() -> usize { super::admission::JURY_MAX_SIZE }
fn default_probation_min_tasks() -> u32 { super::admission::PROBATION_MIN_TASKS }
fn default_probation_max_tasks() -> u32 { super::admission::PROBATION_MAX_TASKS }
fn default_admission_test_timeout() -> Duration { super::admission::TEST_TIMEOUT }
fn default_admission_verdict_timeout() -> Duration { super::admission::VERDICT_TIMEOUT }
fn default_admission_failure_threshold() -> f32 { super::admission::FAILURE_THRESHOLD }
fn default_juror_penalty() -> f32 { super::admission::JUROR_PENALTY }
fn default_juror_bonus() -> f32 { super::admission::JUROR_BONUS }
fn default_admission_check_interval() -> Duration { super::admission::ADMISSION_CHECK_INTERVAL }
fn default_graduation_success_rate() -> f32 { super::admission::GRADUATION_SUCCESS_RATE }
fn default_rate_limit_max_requests() -> u32 { super::admission::RATE_LIMIT_MAX_REQUESTS }
fn default_rate_limit_window() -> Duration { super::admission::RATE_LIMIT_WINDOW }
fn default_nonce_cache_size() -> usize { super::admission::NONCE_CACHE_SIZE }
fn default_cpu_hash_iterations() -> u64 { super::admission::CPU_HASH_ITERATIONS_PER_CORE }

/// Transport tuning configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransportTuningConfig {
    #[serde(default = "default_transport_connect_timeout", with = "humantime_serde")]
    pub connect_timeout: Duration,
    #[serde(default = "default_transport_read_timeout", with = "humantime_serde")]
    pub read_timeout: Duration,
    #[serde(default = "default_transport_idle_timeout", with = "humantime_serde")]
    pub idle_timeout: Duration,
    #[serde(default = "default_max_outbound_connections")]
    pub max_outbound_connections: usize,
    #[serde(default = "default_max_inbound_per_ip")]
    pub max_inbound_connections_per_ip: usize,
    #[serde(default = "default_listen_backlog")]
    pub listen_backlog: u32,
    #[serde(default = "default_channel_capacity")]
    pub channel_capacity: usize,
}

impl Default for TransportTuningConfig {
    fn default() -> Self {
        Self {
            connect_timeout: TRANSPORT_CONNECT_TIMEOUT,
            read_timeout: TRANSPORT_READ_TIMEOUT,
            idle_timeout: CONNECTION_IDLE_TIMEOUT,
            max_outbound_connections: crate::swarm::hardware::get_bounds().max_outbound_connections,
            max_inbound_connections_per_ip: 50,
            listen_backlog: LISTEN_BACKLOG,
            channel_capacity: 1024,
        }
    }
}

fn default_transport_connect_timeout() -> Duration { TRANSPORT_CONNECT_TIMEOUT }
fn default_transport_read_timeout() -> Duration { TRANSPORT_READ_TIMEOUT }
fn default_transport_idle_timeout() -> Duration { CONNECTION_IDLE_TIMEOUT }

fn default_max_inbound_per_ip() -> usize {
    50
}
fn default_max_outbound_connections() -> usize { crate::swarm::hardware::get_bounds().max_outbound_connections }
fn default_listen_backlog() -> u32 { LISTEN_BACKLOG }
fn default_channel_capacity() -> usize { 1024 }

/// Gossip tuning configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GossipTuningConfig {
    #[serde(default = "default_gossip_jitter_percent")]
    pub jitter_percent: u32,
    #[serde(default = "default_gossip_same_region_ratio")]
    pub same_region_ratio: f32,
    #[serde(default = "default_gossip_max_nodes_per_message")]
    pub max_nodes_per_message: usize,
    #[serde(default = "default_gossip_max_jobs_per_message")]
    pub max_jobs_per_message: usize,
    #[serde(default = "default_gossip_max_assignments_per_message")]
    pub max_assignments_per_message: usize,
    #[serde(default = "default_gossip_max_collectives_per_message")]
    pub max_collectives_per_message: usize,
    #[serde(default = "default_gossip_max_profiles_per_message")]
    pub max_profiles_per_message: usize,
    #[serde(default = "default_gossip_max_reputation_per_message")]
    pub max_reputation_per_message: usize,
    #[serde(default = "default_gossip_max_postings_per_message")]
    pub max_postings_per_message: usize,
    #[serde(default = "default_gossip_max_message_size")]
    pub max_message_size: usize,
}

impl Default for GossipTuningConfig {
    fn default() -> Self {
        Self {
            jitter_percent: GOSSIP_JITTER_PERCENT,
            same_region_ratio: GOSSIP_SAME_REGION_RATIO,
            max_nodes_per_message: MAX_NODES_PER_MESSAGE,
            max_jobs_per_message: MAX_JOBS_PER_MESSAGE,
            max_assignments_per_message: MAX_ASSIGNMENTS_PER_MESSAGE,
            max_collectives_per_message: MAX_COLLECTIVES_PER_MESSAGE,
            max_profiles_per_message: MAX_PROFILES_PER_MESSAGE,
            max_reputation_per_message: MAX_REPUTATION_PER_MESSAGE,
            max_postings_per_message: MAX_POSTINGS_PER_MESSAGE,
            max_message_size: MAX_MESSAGE_SIZE,
        }
    }
}

fn default_gossip_jitter_percent() -> u32 { GOSSIP_JITTER_PERCENT }
fn default_gossip_same_region_ratio() -> f32 { GOSSIP_SAME_REGION_RATIO }
fn default_gossip_max_nodes_per_message() -> usize { MAX_NODES_PER_MESSAGE }
fn default_gossip_max_jobs_per_message() -> usize { MAX_JOBS_PER_MESSAGE }
fn default_gossip_max_assignments_per_message() -> usize { MAX_ASSIGNMENTS_PER_MESSAGE }
fn default_gossip_max_collectives_per_message() -> usize { MAX_COLLECTIVES_PER_MESSAGE }
fn default_gossip_max_profiles_per_message() -> usize { MAX_PROFILES_PER_MESSAGE }
fn default_gossip_max_reputation_per_message() -> usize { MAX_REPUTATION_PER_MESSAGE }
fn default_gossip_max_postings_per_message() -> usize { MAX_POSTINGS_PER_MESSAGE }
fn default_gossip_max_message_size() -> usize { MAX_MESSAGE_SIZE }

/// Trait evaluation tuning configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraitEvalConfig {
    #[serde(default = "default_trait_jitter_percent")]
    pub jitter_percent: u32,
    #[serde(default = "default_trait_eval_interval", with = "humantime_serde")]
    pub eval_interval: Duration,
    #[serde(default = "default_threshold_execute_cpu")]
    pub threshold_execute_cpu: f32,
    #[serde(default = "default_threshold_aggregate_ram_mb")]
    pub threshold_aggregate_ram_mb: u64,
    #[serde(default = "default_threshold_forward_load")]
    pub threshold_forward_load: f32,
    #[serde(default = "default_threshold_store_disk_mb")]
    pub threshold_store_disk_mb: u64,
    #[serde(default = "default_threshold_relay_bandwidth_mbps")]
    pub threshold_relay_bandwidth_mbps: f32,
    #[serde(default = "default_max_relay_load")]
    pub max_relay_load: f32,
    #[serde(default = "default_default_bandwidth_mbps")]
    pub default_bandwidth_mbps: f32,
}

impl Default for TraitEvalConfig {
    fn default() -> Self {
        Self {
            jitter_percent: GOSSIP_JITTER_PERCENT, // reuse same default
            eval_interval: TRAIT_EVAL_INTERVAL,
            threshold_execute_cpu: THRESHOLD_EXECUTE_CPU,
            threshold_aggregate_ram_mb: THRESHOLD_AGGREGATE_RAM_MB,
            threshold_forward_load: THRESHOLD_FORWARD_LOAD,
            threshold_store_disk_mb: THRESHOLD_STORE_DISK_MB,
            threshold_relay_bandwidth_mbps: THRESHOLD_RELAY_BANDWIDTH_MBPS,
            max_relay_load: 0.5,
            default_bandwidth_mbps: 100.0,
        }
    }
}

fn default_trait_jitter_percent() -> u32 { GOSSIP_JITTER_PERCENT }
fn default_trait_eval_interval() -> Duration { TRAIT_EVAL_INTERVAL }
fn default_threshold_execute_cpu() -> f32 { THRESHOLD_EXECUTE_CPU }
fn default_threshold_aggregate_ram_mb() -> u64 { THRESHOLD_AGGREGATE_RAM_MB }
fn default_threshold_forward_load() -> f32 { THRESHOLD_FORWARD_LOAD }
fn default_threshold_store_disk_mb() -> u64 { THRESHOLD_STORE_DISK_MB }
fn default_threshold_relay_bandwidth_mbps() -> f32 { THRESHOLD_RELAY_BANDWIDTH_MBPS }
fn default_max_relay_load() -> f32 { 0.5 }
fn default_default_bandwidth_mbps() -> f32 { 100.0 }

/// Work distribution tuning configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkTuningConfig {
    #[serde(default = "default_work_check_interval", with = "humantime_serde")]
    pub check_interval: Duration,
    #[serde(default = "default_max_chunk_attempts")]
    pub max_chunk_attempts: u32,
    #[serde(default = "default_conflict_backoff", with = "humantime_serde")]
    pub conflict_backoff: Duration,
    #[serde(default = "default_max_pending_chunks")]
    pub max_pending_chunks: usize,
    #[serde(default = "default_aggregation_check_interval", with = "humantime_serde")]
    pub aggregation_check_interval: Duration,
}

impl Default for WorkTuningConfig {
    fn default() -> Self {
        Self {
            check_interval: WORK_CHECK_INTERVAL,
            max_chunk_attempts: MAX_CHUNK_ATTEMPTS,
            conflict_backoff: CONFLICT_BACKOFF,
            max_pending_chunks: MAX_PENDING_CHUNKS,
            aggregation_check_interval: Duration::from_secs(2),
        }
    }
}

fn default_work_check_interval() -> Duration { WORK_CHECK_INTERVAL }
fn default_max_chunk_attempts() -> u32 { MAX_CHUNK_ATTEMPTS }
fn default_conflict_backoff() -> Duration { CONFLICT_BACKOFF }
fn default_max_pending_chunks() -> usize { MAX_PENDING_CHUNKS }
fn default_aggregation_check_interval() -> Duration { Duration::from_secs(2) }

// ============================================================================
// Runtime-overridable configuration
// ============================================================================

/// Full swarm configuration, overridable at runtime via config file or env.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwarmConfig {
    /// This node's listen address (e.g., "0.0.0.0:4200")
    pub listen_addr: String,

    /// Bootstrap/seed server addresses
    pub bootstrap_servers: Vec<String>,

    /// Gossip interval override
    #[serde(with = "humantime_serde")]
    pub gossip_interval: Duration,

    /// Gossip fanout override
    pub gossip_fanout: usize,

    /// Failure detection: suspect threshold
    #[serde(with = "humantime_serde")]
    pub suspect_threshold: Duration,

    /// Failure detection: dead threshold
    #[serde(with = "humantime_serde")]
    pub dead_threshold: Duration,

    /// Maximum concurrent chunk executions
    pub max_concurrent_chunks: usize,

    /// Maximum load threshold
    pub max_load: f32,

    /// Chunk execution timeout
    #[serde(with = "humantime_serde")]
    pub chunk_timeout: Duration,

    /// Path to persist node identity (NodeId + generation)
    pub identity_file: Option<String>,

    /// Path to persist swarm state (for can_store_state nodes)
    pub state_dir: Option<String>,

    /// Traits to force-enable regardless of resource evaluation
    #[serde(default)]
    pub force_traits: Vec<String>,

    /// Traits to force-disable regardless of resource evaluation
    #[serde(default)]
    pub deny_traits: Vec<String>,

    /// Node type hint (e.g., "bare-metal", "cloud-vm", "mobile", "raspberry-pi")
    #[serde(default)]
    pub node_type: Option<String>,

    /// Maximum number of collectives this node may join
    #[serde(default = "default_max_collectives")]
    pub max_collectives: usize,

    /// Bidding window duration for marketplace postings
    #[serde(default = "default_bid_window", with = "humantime_serde")]
    pub bid_window: Duration,

    /// Minimum capability match score to be eligible for a posting
    #[serde(default = "default_min_capability_match")]
    pub min_capability_match: f32,

    /// Number of recent jobs in the rolling reputation window
    #[serde(default = "default_reputation_window_size")]
    pub reputation_window_size: usize,

    /// Override for the energy cost weight in marketplace scoring.
    /// When set, replaces the compile-time `SCORING_WEIGHT_ENERGY` constant.
    #[serde(default)]
    pub scoring_weight_energy: Option<f64>,

    /// Plugin host configuration (optional — no plugins loaded if absent).
    #[serde(default)]
    pub plugin_host: Option<crate::plugin::config::PluginHostConfig>,

    /// Whether API authentication is required (default true).
    ///
    /// When `false`, all routes are accessible without a bearer token.
    /// Useful for local development and testing.
    #[serde(default = "default_api_auth_required")]
    pub api_auth_required: bool,

    /// Path to a file where the initial admin token is written on first run.
    ///
    /// If the file does not exist when the node starts, a fresh admin token
    /// is generated and written here. If the file already exists, no new
    /// token is generated.
    #[serde(default)]
    pub admin_token_file: Option<PathBuf>,

    /// Pre-configured data residency policies loaded from config file.
    /// These are merged into the node's PolicySet on startup.
    #[serde(default)]
    pub data_residency_policies: Vec<super::policy::DataResidencyPolicy>,

    /// Whether auto-update is enabled (default: false, opt-in).
    #[serde(default)]
    pub auto_update: bool,

    /// URL of the update server to check for new versions.
    /// The manifest is fetched from `{update_url}/latest.json`.
    #[serde(default)]
    pub update_url: Option<String>,

    /// Whether to enable the PostgreSQL wire protocol (PgWire) on port 5432.
    #[serde(default)]
    pub enable_pgwire: bool,

    /// Whether to enable the Amazon S3-compatible Proxy Gateway on port 9000.
    #[serde(default)]
    pub enable_s3_gateway: bool,

    /// Whether to enable the Planetary Redis protocol (RESP) on port 6379.
    #[serde(default)]
    pub enable_redis: bool,

    /// How often to check for updates (default: 6 hours).
    #[serde(default = "default_update_check_interval", with = "humantime_serde")]
    pub update_check_interval: Duration,

    /// Ed25519 public key (base64-encoded) for verifying release signatures.
    #[serde(default)]
    pub update_signing_key: Option<String>,

    // === Management layer fields ===

    /// Human-readable swarm name.
    #[serde(default = "default_swarm_name")]
    pub swarm_name: String,

    /// Swarm description.
    #[serde(default)]
    pub swarm_description: String,

    /// Path to swarm identity keypair file (auto-generated if absent).
    #[serde(default)]
    pub swarm_identity_file: Option<String>,

    /// Path to management UI static files directory (None = disabled).
    #[serde(default)]
    pub management_ui_dir: Option<String>,

    /// Path to custom archetypes TOML file (None = builtins only).
    #[serde(default)]
    pub archetypes_file: Option<String>,

    /// Path to custom visions TOML file (None = builtins only).
    #[serde(default)]
    pub visions_file: Option<String>,

    /// Path to alert rules file (None = builtin rules only).
    #[serde(default)]
    pub alert_rules_file: Option<String>,

    /// Path to SLA definitions file (None = default SLAs only).
    #[serde(default)]
    pub sla_definitions_file: Option<String>,

    /// Path to audit log persistence file (None = in-memory only).
    #[serde(default)]
    pub audit_log_file: Option<String>,

    /// Whether to enable the management layer subsystems.
    #[serde(default = "default_enable_management_layer")]
    pub enable_management_layer: bool,

    /// Whether to enable the Neuromancer intelligence/security_domain subsystem.
    #[serde(default)]
    pub enable_neuromancer: bool,

    /// Neuromancer subsystem configuration (optional; defaults used when None).
    #[serde(default)]
    pub neuromancer: Option<super::neuromancer::config::NeuromancerConfig>,

    /// Whether to enable the swarm-managed PostgreSQL subsystem.
    ///
    /// When true (the default for non-minimal deployments), the swarm
    /// automatically deploys and manages PostgreSQL on capable nodes
    /// (≥4 GB RAM, ≥2 GB disk). Provides the backing store for config
    /// history, time-travel queries, audit trails, and compliance records.
    #[serde(default = "default_enable_postgres")]
    pub enable_postgres: bool,

    /// PostgreSQL subsystem configuration (optional; defaults used when None).
    #[serde(default)]
    pub postgres: Option<super::postgres::config::PgConfig>,

    // === Sub-configuration structs (promoted from constants) ===

    /// Admission subsystem tuning.
    #[serde(default)]
    pub admission: AdmissionConfig,

    /// Transport tuning.
    #[serde(default)]
    pub transport_tuning: TransportTuningConfig,

    /// Gossip tuning.
    #[serde(default)]
    pub gossip_tuning: GossipTuningConfig,

    /// Trait evaluation tuning.
    #[serde(default)]
    pub trait_eval: TraitEvalConfig,

    /// Work distribution tuning.
    #[serde(default)]
    pub work_tuning: WorkTuningConfig,

    /// Whether the Observe-and-Interfere subsystem is enabled.
    #[serde(default)]
    pub enable_observe_and_interfere: bool,

    /// OAI configuration (only used when enable_observe_and_interfere is true).
    #[serde(default)]
    pub observe_and_interfere: Option<super::observe::config::OaiConfig>,

    // === EU Highestsec Compliance fields ===

    /// Whether Software-Only Blind Computing (FHE + ZKP) is enabled.
    #[serde(default)]
    pub enable_blind_computation: bool,

    /// Whether highestsec zone enforcement is enabled.
    #[serde(default)]
    pub enable_highestsec_zones: bool,

    /// Highestsec zone configuration (only used when enable_highestsec_zones is true).
    #[serde(default)]
    pub highestsec_zone: Option<HighestsecZoneConfig>,

    /// Whether to accept unsigned gossip messages (migration mode).
    /// Default: false (unsigned gossip is rejected).
    #[serde(default)]
    pub allow_unsigned_gossip: bool,

    /// TLS certificate PEM file path.
    #[serde(default)]
    pub tls_cert_path: Option<String>,

    /// TLS private key PEM file path.
    #[serde(default)]
    pub tls_key_path: Option<String>,

    /// Allow plaintext transport (development/testing only).
    /// Default: false.
    #[serde(default)]
    pub allow_plaintext: bool,

    /// Auto-generate self-signed TLS certificates for dev mode.
    #[serde(default = "default_true")]
    pub auto_generate_tls: bool,

    /// WebSocket control plane authentication token.
    /// If not set, a cryptographically random token is generated at startup.
    /// Must be at least 16 characters if explicitly set.
    #[serde(default)]
    pub websocket_auth_token: Option<String>,

    /// Whether GDPR right-to-erasure engine is enabled.
    /// Default: true (GDPR should be on by default for EU compliance).
    #[serde(default = "default_true")]
    pub enable_gdpr: bool,

    /// Whether the Phantom protocol (cover traffic) is enabled.
    #[serde(default)]
    pub enable_phantom_protocol: bool,

    /// GDPR engine configuration (only used when enable_gdpr is true).
    #[serde(default)]
    pub gdpr: Option<super::gdpr::GdprConfig>,
}

impl Default for SwarmConfig {
    fn default() -> Self {
        Self {
            listen_addr: "0.0.0.0:4200".to_string(),
            bootstrap_servers: Vec::new(),
            gossip_interval: GOSSIP_INTERVAL,
            gossip_fanout: GOSSIP_FANOUT,
            suspect_threshold: SUSPECT_THRESHOLD,
            dead_threshold: DEAD_THRESHOLD,
            max_concurrent_chunks: MAX_CONCURRENT_CHUNKS,
            max_load: MAX_LOAD_THRESHOLD,
            chunk_timeout: CHUNK_TIMEOUT,
            identity_file: None,
            state_dir: None,
            force_traits: Vec::new(),
            deny_traits: Vec::new(),
            node_type: None,
            max_collectives: MAX_COLLECTIVES_PER_NODE,
            bid_window: BID_WINDOW,
            min_capability_match: MIN_CAPABILITY_MATCH,
            reputation_window_size: ROLLING_WINDOW_SIZE,
            scoring_weight_energy: None,
            plugin_host: None,
            api_auth_required: false,
            admin_token_file: None,
            data_residency_policies: Vec::new(),
            auto_update: false,
            update_url: None,
            update_check_interval: UPDATE_CHECK_INTERVAL,
            update_signing_key: None,
            swarm_name: "unnamed-swarm".to_string(),
            swarm_description: String::new(),
            swarm_identity_file: None,
            management_ui_dir: None,
            archetypes_file: None,
            visions_file: None,
            alert_rules_file: None,
            sla_definitions_file: None,
            audit_log_file: None,
            enable_management_layer: true,
            enable_neuromancer: false,
            neuromancer: None,
            enable_postgres: true,
            postgres: None,
            admission: AdmissionConfig::default(),
            transport_tuning: TransportTuningConfig::default(),
            gossip_tuning: GossipTuningConfig::default(),
            trait_eval: TraitEvalConfig::default(),
            work_tuning: WorkTuningConfig::default(),
            enable_observe_and_interfere: false,
            observe_and_interfere: None,
            enable_blind_computation: false,
            enable_highestsec_zones: false,
            highestsec_zone: None,
            allow_unsigned_gossip: false,
            tls_cert_path: None,
            tls_key_path: None,
            allow_plaintext: false,
            auto_generate_tls: true,
            websocket_auth_token: None,
            enable_gdpr: true,
            enable_phantom_protocol: false,
            gdpr: None,
            enable_pgwire: false,
            enable_s3_gateway: false,
            enable_redis: false,
        }
    }
}

impl SwarmConfig {
    /// Validate configuration consistency. Returns an error message if invalid.
    pub fn validate(&self) -> Result<(), String> {
        // Enforce TLS when blind computation or highestsec zones are enabled
        if (self.enable_blind_computation || self.enable_highestsec_zones) && self.allow_plaintext {
            return Err(
                "allow_plaintext must be false when blind computation or highestsec zones are enabled"
                    .into(),
            );
        }
        // Reject unsigned gossip when blind computation is enabled
        if self.enable_blind_computation && self.allow_unsigned_gossip {
            return Err(
                "allow_unsigned_gossip must be false when blind computation is enabled. \
                 Unsigned gossip allows message forgery which undermines blind computation trust."
                    .into(),
            );
        }
        // Blind computation requires highestsec zones for zone enforcement
        if self.enable_blind_computation && !self.enable_highestsec_zones {
            return Err(
                "enable_highestsec_zones must be true when blind computation is enabled. \
                 Blind computation requires mandatory zone ID enforcement."
                    .into(),
            );
        }
        // Blind computation requires neuromancer for incident response
        if self.enable_blind_computation && !self.enable_neuromancer {
            return Err(
                "enable_neuromancer must be true when blind computation is enabled. \
                 Blind computation workloads require anomaly detection and incident response."
                    .into(),
            );
        }
        // Validate websocket auth token if provided
        if let Some(ref token) = self.websocket_auth_token {
            if token.len() < 16 {
                return Err("websocket_auth_token must be at least 16 characters".into());
            }
            const WEAK_TOKENS: &[&str] = &[
                "default-token",
                "password",
                "admin",
                "secret",
                "changeme",
                "test-token",
                "your-secure-token-here",
            ];
            if WEAK_TOKENS.contains(&token.as_str()) {
                return Err(format!(
                    "websocket_auth_token is a known weak value: '{token}'"
                ));
            }
        }
        Ok(())
    }
}

// Serde default helpers for the new SwarmConfig fields

fn default_max_collectives() -> usize {
    MAX_COLLECTIVES_PER_NODE
}

fn default_bid_window() -> Duration {
    BID_WINDOW
}

fn default_min_capability_match() -> f32 {
    MIN_CAPABILITY_MATCH
}

fn default_reputation_window_size() -> usize {
    ROLLING_WINDOW_SIZE
}

fn default_api_auth_required() -> bool {
    true
}

fn default_update_check_interval() -> Duration {
    UPDATE_CHECK_INTERVAL
}

fn default_blind_min_trust_score() -> f64 {
    0.8
}

fn default_blind_min_verified_jobs() -> u64 {
    50
}

fn default_swarm_name() -> String {
    "unnamed-swarm".to_string()
}

fn default_enable_management_layer() -> bool {
    true
}

fn default_enable_postgres() -> bool {
    true
}

fn default_true() -> bool {
    true
}

fn default_blind_cover_traffic_delay_ms() -> Option<u64> {
    None
}

// ═══════════════════════════════════════════════════════════════════════════
// EU Highestsec Compliance Configuration
// ═══════════════════════════════════════════════════════════════════════════

/// Maximum zone certificates gossipped per message.
pub const MAX_ZONE_CERTS_PER_MESSAGE: usize = 50;

/// Configuration for highestsec zone enforcement.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[derive(Default)]
pub struct HighestsecZoneConfig {
    /// Path to the zone authority signing key (PEM or raw).
    #[serde(default)]
    pub authority_key_path: Option<String>,

    /// Initial zone ID this node belongs to.
    #[serde(default)]
    pub initial_zone_id: Option<String>,

    /// Jurisdiction (ISO country code) for this node.
    #[serde(default)]
    pub jurisdiction: Option<String>,
}


// ═══════════════════════════════════════════════════════════════════════════
// Combo Infrastructure Constants
// ═══════════════════════════════════════════════════════════════════════════

/// Default verification replicas for redundant execution.
pub const VERIFICATION_DEFAULT_REPLICAS: u8 = 2;
/// Maximum replicas for redundant execution.
pub const VERIFICATION_MAX_REPLICAS: u8 = 5;
/// Spot check rate for trusted nodes (5%).
pub const VERIFICATION_SPOT_CHECK_RATE: f64 = 0.05;
/// Statistical outlier tolerance (z-score threshold).
pub const VERIFICATION_OUTLIER_Z_SCORE: f64 = 3.0;
/// Minimum jobs before a node qualifies for spot-check (instead of redundant).
pub const VERIFICATION_TRUST_THRESHOLD_JOBS: u64 = 100;
/// Maximum time to wait for all replicas before declaring timeout (seconds).
pub const VERIFICATION_REPLICA_TIMEOUT_SECS: u64 = 300;
/// How long to cache verification hashes (seconds).
pub const VERIFICATION_HASH_CACHE_TTL_SECS: u64 = 3600;

/// Base cost per node-hour in USD.
pub const PRICING_BASE_NODE_HOUR_USD: f64 = 0.002;
/// Platform transaction fee percentage (2%).
pub const PRICING_TRANSACTION_FEE_PCT: f64 = 0.02;
/// Rush priority cost multiplier.
pub const PRICING_RUSH_MULTIPLIER: f64 = 3.0;
/// Economy priority cost multiplier.
pub const PRICING_ECONOMY_MULTIPLIER: f64 = 0.5;
/// Expected retry overhead percentage for cost estimation.
pub const PRICING_RETRY_OVERHEAD_PCT: f64 = 0.20;
/// Expected verification overhead for redundant (2x) mode.
pub const PRICING_VERIFICATION_OVERHEAD_2X: f64 = 1.0;
/// Expected verification overhead for spot-check mode.
pub const PRICING_VERIFICATION_OVERHEAD_SPOT: f64 = 0.08;

/// Webhook delivery timeout per request in seconds.
pub const WEBHOOK_TIMEOUT_SECS: u64 = 30;
/// Maximum webhook delivery retries.
pub const WEBHOOK_MAX_RETRIES: u8 = 5;
/// Webhook retry backoff base in seconds.
pub const WEBHOOK_RETRY_BACKOFF_BASE_SECS: u64 = 5;
/// Maximum concurrent webhook deliveries.
pub const WEBHOOK_MAX_CONCURRENT: usize = 32;

/// SSE keep-alive interval in seconds.
pub const SSE_KEEPALIVE_SECS: u64 = 15;
/// Maximum SSE connections per job.
pub const SSE_MAX_CONNECTIONS_PER_JOB: usize = 50;
/// SSE buffer size per connection.
pub const SSE_BUFFER_SIZE: usize = 256;

/// Scheduler tick interval in milliseconds.
pub const SCHEDULER_TICK_MS: u64 = 500;
/// Economy jobs: off-peak hours (start hour, UTC).
pub const SCHEDULER_OFFPEAK_START_HOUR: u32 = 22;
/// Economy jobs: off-peak hours (end hour, UTC).
pub const SCHEDULER_OFFPEAK_END_HOUR: u32 = 6;
/// Maximum queue depth before rejecting new jobs.
pub const SCHEDULER_MAX_QUEUE_DEPTH: usize = 10_000;
/// Rush jobs: fraction of swarm capacity reserved.
pub const SCHEDULER_RUSH_RESERVE_FRACTION: f64 = 0.30;

/// Node class: Edge memory threshold (MB).
pub const NODE_CLASS_DUST_MAX_MEMORY_MB: u64 = 1_500;
/// Node class: Light memory threshold (MB).
pub const NODE_CLASS_PEBBLE_MAX_MEMORY_MB: u64 = 6_000;
/// Node class: Standard memory threshold (MB).
pub const NODE_CLASS_ROCK_MAX_MEMORY_MB: u64 = 20_000;
/// Node class: Light max cores.
pub const NODE_CLASS_PEBBLE_MAX_CORES: u32 = 4;
/// Node class: Standard max cores.
pub const NODE_CLASS_ROCK_MAX_CORES: u32 = 8;

// ============================================================================
// Timestamp trust & drift quarantine (Hardening A.1)
// ============================================================================

/// Maximum acceptable clock drift before clamping.
/// Timestamps within this window are silently clamped to `now + MAX_ACCEPTABLE_DRIFT`.
pub const MAX_ACCEPTABLE_DRIFT: Duration = Duration::from_secs(5);

/// Drift beyond this threshold causes the entire gossip message to be rejected.
pub const DRIFT_REJECT_THRESHOLD: Duration = Duration::from_secs(30);

/// Number of drift violations within the quarantine window before auto-quarantine.
pub const ANOMALY_QUARANTINE_THRESHOLD: u32 = 10;

/// Sliding window for counting drift violations.
pub const ANOMALY_QUARANTINE_WINDOW: Duration = Duration::from_secs(60);

// ============================================================================
// Additional message bounds (Hardening A.8)
// ============================================================================

/// Maximum software inventory entries per gossip message.
pub const MAX_SOFTWARE_INVENTORIES_PER_MESSAGE: usize = 50;

// ============================================================================
// Scrutiny & Witness Configuration (Audit W1A)
// ============================================================================
//
// These constants govern the adaptive scrutiny model introduced in W1A.
// They are distinct from the existing WITNESS_DECAY_SECS and
// MAX_WITNESS_REPORTS_PER_MESSAGE constants, which serve the *failure
// detection* subsystem. Both systems coexist.

/// Witness response timeout for Low-criticality actions (seconds).
/// Low actions require no witnesses, so the timeout is zero.
pub const SCRUTINY_WITNESS_TIMEOUT_LOW: u64 = 0;

/// Witness response timeout for Normal-criticality actions (seconds).
pub const SCRUTINY_WITNESS_TIMEOUT_NORMAL: u64 = 5;

/// Witness response timeout for High-criticality actions (seconds).
pub const SCRUTINY_WITNESS_TIMEOUT_HIGH: u64 = 10;

/// Witness response timeout for Critical-criticality actions (seconds).
pub const SCRUTINY_WITNESS_TIMEOUT_CRITICAL: u64 = 30;

/// Witness response timeout for Emergency-criticality actions (seconds).
pub const SCRUTINY_WITNESS_TIMEOUT_EMERGENCY: u64 = 60;

/// Minimum distinct network segments for High-tier witnesses.
pub const MIN_WITNESS_SEGMENTS_HIGH: usize = 2;

/// Minimum distinct network segments for Critical-tier witnesses.
pub const MIN_WITNESS_SEGMENTS_CRITICAL: usize = 3;

/// Required witnesses for Normal-tier actions.
pub const WITNESS_COUNT_NORMAL: usize = 2;

/// Required witnesses for High-tier actions.
pub const WITNESS_COUNT_HIGH: usize = 5;

/// Minimum witnesses for Critical-tier actions.
pub const WITNESS_COUNT_CRITICAL: usize = 7;

/// How often the scrutiny engine re-evaluates action-type mappings
/// against configuration changes (seconds).
pub const SCRUTINY_RESCAN_INTERVAL_SECS: u64 = 300;

// ============================================================================
// Workflow Lock Configuration (W3A)
// ============================================================================

/// TTL for workflow instance distributed locks (seconds).
pub const WF_LOCK_TTL_SECS: u32 = 30;

/// Delay between lock acquisition retry attempts (milliseconds).
pub const WF_LOCK_RETRY_MS: u64 = 100;

/// Maximum number of lock acquisition retries before giving up.
pub const WF_LOCK_MAX_RETRIES: u32 = 50;

/// TTL for partial approval entries (seconds). Default 1 hour.
pub const WF_APPROVAL_TTL_SECS: u64 = 3600;

// ============================================================================
// Timer Service Configuration (W3C)
// ============================================================================

/// How often the timer polling loop checks for expired timers (seconds).
pub const TIMER_CHECK_INTERVAL_SECS: u64 = 10;

// ============================================================================
// Witness Consensus Protocol (W3D)
// ============================================================================

/// Quorum ratio for Normal-tier witnesses (all 2 must confirm).
pub const WITNESS_QUORUM_RATIO_NORMAL: f64 = 1.0;

/// Quorum ratio for High-tier witnesses (supermajority: 4 of 5).
pub const WITNESS_QUORUM_RATIO_HIGH: f64 = 0.8;

/// Quorum ratio for Critical-tier witnesses (supermajority: 5 of 7).
pub const WITNESS_QUORUM_RATIO_CRITICAL: f64 = 0.72;

/// Background signature re-verification interval (seconds).
pub const WITNESS_BG_VERIFY_INTERVAL_SECS: u64 = 120;

/// Maximum concurrent in-flight witness rounds.
pub const WITNESS_MAX_CONCURRENT_ROUNDS: usize = 16;

/// Delay before retrying a failed witness request (milliseconds).
pub const WITNESS_RETRY_DELAY_MS: u64 = 500;

/// Timeout for audit trail reconstruction sync requests (seconds).
pub const AUDIT_SYNC_TIMEOUT_SECS: u64 = 10;

/// Returns the witness requirements for a given criticality level.
///
/// Returns `(witness_count, min_segments)`:
/// - Low:       (0, 0)        -- no witnesses needed
/// - Normal:    (2, 1)        -- 2 witnesses, any segment
/// - High:      (5, 2)        -- 5 witnesses, 2+ segments
/// - Critical:  (7, 3)        -- 7+ witnesses, 3+ segments
/// - Emergency: (MAX, MAX)    -- all reachable nodes, all segments
pub fn witness_requirements(level: &super::types::CriticalityLevel) -> (usize, usize) {
    use super::types::CriticalityLevel;
    match level {
        CriticalityLevel::Low       => (0, 0),
        CriticalityLevel::Normal    => (WITNESS_COUNT_NORMAL, 1),
        CriticalityLevel::High      => (WITNESS_COUNT_HIGH, MIN_WITNESS_SEGMENTS_HIGH),
        CriticalityLevel::Critical  => (WITNESS_COUNT_CRITICAL, MIN_WITNESS_SEGMENTS_CRITICAL),
        CriticalityLevel::Emergency => (usize::MAX, usize::MAX),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_rejects_blind_with_seccomp_log_only() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.allow_plaintext = false;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: true,
            additional_allowed: vec![],
        });
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_config_accepts_blind_with_seccomp_enforce() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.enable_highestsec_zones = true;
        config.enable_neuromancer = true;
        config.allow_plaintext = false;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: false,
            additional_allowed: vec![],
        });
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_config_rejects_blind_without_highestsec_zones() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.enable_highestsec_zones = false;
        config.allow_plaintext = false;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: false,
            additional_allowed: vec![],
        });
        let err = config.validate().unwrap_err();
        assert!(
            err.contains("enable_highestsec_zones must be true"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_config_blind_no_seccomp_field_rejected() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.allow_plaintext = false;
        // seccomp is None — must be rejected now (FIX P2-10)
        let err = config.validate().unwrap_err();
        assert!(
            err.contains("seccomp configuration must be provided"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_config_rejects_blind_with_unsigned_gossip() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.allow_plaintext = false;
        config.allow_unsigned_gossip = true;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: false,
            additional_allowed: vec![],
        });
        let err = config.validate().unwrap_err();
        assert!(
            err.contains("allow_unsigned_gossip must be false"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_config_rejects_blind_without_neuromancer() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.enable_highestsec_zones = true;
        config.enable_neuromancer = false;
        config.allow_plaintext = false;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: false,
            additional_allowed: vec![],
        });
        let err = config.validate().unwrap_err();
        assert!(
            err.contains("enable_neuromancer must be true"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_config_rejects_blind_with_forbidden_additional_allowed() {
        let mut config = SwarmConfig::default();
        config.enable_blind_execution = true;
        config.enable_highestsec_zones = true;
        config.enable_neuromancer = true;
        config.allow_plaintext = false;
        config.seccomp = Some(crate::highestsec::seccomp::SeccompConfig {
            enabled: true,
            log_only: false,
            additional_allowed: vec!["socket".to_string()],
        });
        let err = config.validate().unwrap_err();
        assert!(
            err.contains("blind computation forbids 'socket'"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_default_blind_trust_fields() {
        let config = SwarmConfig::default();
        assert!((config.blind_min_trust_score - 0.8).abs() < f64::EPSILON);
        assert_eq!(config.blind_min_verified_jobs, 50);
    }
}


// Trusted beacon nodes for latency triangulation to determine physical location.

// --- MARABUNTA CONFIGURATION CONSTANTS ---
pub const BEACON_NODES: &[&str] = &["1.1.1.1:80", "8.8.8.8:53"];


