import fitz

# Goal: Parse the exact text, fonts, colors, and layout from the original PDF.
# Then, apply the requested changes and generate a new PDF maintaining the exact structure.
# Since we know the PDF was generated by "LaTeX via pandoc", we can try to extract the logical blocks.

doc = fitz.open("400_eng_rbattaglia_cv.pdf")

for page_num in range(len(doc)):
    page = doc[page_num]
    # Extract blocks
    blocks = page.get_text("dict")["blocks"]
    for b in blocks:
        if "lines" not in b:
            continue
        for l in b["lines"]:
            text = "".join([s["text"] for s in l["spans"]])
            if "Marabunta HPC" in text or "July 2024" in text:
                print(f"Bbox: {b['bbox']}, Text: {text}")

