#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Installs the Marabunta Compute Swarm Node as a Windows Service.

.DESCRIPTION
    This script copies the swarm binary to Program Files, generates a default
    configuration file, registers the Windows Service with automatic startup
    and failure-recovery settings, adds firewall rules, and starts the service.

.PARAMETER BinaryPath
    Path to the compiled marabunta-swarm-service.exe binary.

.PARAMETER ConfigPath
    Path where the TOML configuration file will be written.

.PARAMETER DataDir
    Directory for persistent swarm data (identity, state, blobs).

.PARAMETER LogDir
    Directory for service log files.

.PARAMETER ServiceName
    Windows Service name (default: MarabuntaSwarm).

.PARAMETER DisplayName
    Display name shown in services.msc.

.PARAMETER ApiPort
    HTTP API port (default: 4201).

.PARAMETER ListenPort
    Gossip/transport listen port (default: 4200).

.PARAMETER BootstrapServers
    Array of bootstrap server addresses (e.g., @("10.0.0.1:4200","10.0.0.2:4200")).

.EXAMPLE
    .\install-windows-service.ps1

.EXAMPLE
    .\install-windows-service.ps1 -BootstrapServers @("seed1.example.com:4200") -ApiPort 8080
#>

param(
    [string]$BinaryPath = "$PSScriptRoot\..\target\release\marabunta-swarm-service.exe",
    [string]$ConfigPath = "$env:ProgramData\MarabuntaCompute\config\swarm.toml",
    [string]$DataDir = "$env:ProgramData\MarabuntaCompute\data",
    [string]$LogDir = "$env:ProgramData\MarabuntaCompute\logs",
    [string]$ServiceName = "MarabuntaSwarm",
    [string]$DisplayName = "Marabunta Compute Swarm Node",
    [int]$ListenPort = 4200,
    [int]$ApiPort = 4201,
    [string[]]$BootstrapServers = @()
)

$ErrorActionPreference = "Stop"

$InstallDir = "$env:ProgramFiles\MarabuntaCompute\bin"
$InstalledBinary = "$InstallDir\marabunta-swarm-service.exe"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Marabunta Compute Swarm Node - Service Installer" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# -------------------------------------------------------------------------
# 1. Validate binary exists
# -------------------------------------------------------------------------
$ResolvedBinary = Resolve-Path $BinaryPath -ErrorAction SilentlyContinue
if (-not $ResolvedBinary) {
    Write-Error "Binary not found at '$BinaryPath'. Build with: cargo build --release --features windows-service --bin marabunta-swarm-service"
    exit 1
}
Write-Host "[1/7] Binary found: $ResolvedBinary" -ForegroundColor Green

# -------------------------------------------------------------------------
# 2. Create directory structure
# -------------------------------------------------------------------------
$Directories = @(
    $InstallDir,
    (Split-Path $ConfigPath -Parent),
    $DataDir,
    $LogDir
)

foreach ($Dir in $Directories) {
    if (-not (Test-Path $Dir)) {
        New-Item -ItemType Directory -Path $Dir -Force | Out-Null
        Write-Host "  Created: $Dir"
    }
}
Write-Host "[2/7] Directories created" -ForegroundColor Green

# -------------------------------------------------------------------------
# 3. Copy binary to Program Files
# -------------------------------------------------------------------------
# Stop the service first if it is running so the binary is not locked.
$ExistingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($ExistingService -and $ExistingService.Status -eq "Running") {
    Write-Host "  Stopping existing service before updating binary..."
    Stop-Service -Name $ServiceName -Force
    Start-Sleep -Seconds 2
}

Copy-Item -Path $ResolvedBinary -Destination $InstalledBinary -Force
Write-Host "[3/7] Binary installed to: $InstalledBinary" -ForegroundColor Green

# -------------------------------------------------------------------------
# 4. Generate default config if it does not exist
# -------------------------------------------------------------------------
if (-not (Test-Path $ConfigPath)) {
    $BootstrapToml = ""
    if ($BootstrapServers.Count -gt 0) {
        $Quoted = $BootstrapServers | ForEach-Object { "`"$_`"" }
        $BootstrapToml = "bootstrap_servers = [$($Quoted -join ', ')]"
    } else {
        $BootstrapToml = "bootstrap_servers = []"
    }

    $ConfigContent = @"
# Marabunta Compute Swarm Node Configuration
# Generated by install-windows-service.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
#
# See https://docs.marabunta-compute.io/config for full reference.

# Network
listen_addr = "0.0.0.0:$ListenPort"
$BootstrapToml

# Gossip protocol
gossip_interval = "1s"
gossip_fanout = 3

# Failure detection
suspect_threshold = "10s"
dead_threshold = "30s"

# Work execution
max_concurrent_chunks = 4
max_load = 0.8
chunk_timeout = "300s"

# Identity persistence (keeps NodeId stable across restarts)
identity_file = "$($DataDir.Replace('\','\\'))\\identity.json"

# State persistence
state_dir = "$($DataDir.Replace('\','\\'))\\state"

# Organic swarm
max_collectives = 3
bid_window = "5s"
min_capability_match = 0.5
"@

    Set-Content -Path $ConfigPath -Value $ConfigContent -Encoding UTF8
    Write-Host "[4/7] Default config written to: $ConfigPath" -ForegroundColor Green
} else {
    Write-Host "[4/7] Config already exists: $ConfigPath (skipped)" -ForegroundColor Yellow
}

# -------------------------------------------------------------------------
# 5. Register the Windows Service
# -------------------------------------------------------------------------
if ($ExistingService) {
    Write-Host "  Service '$ServiceName' already registered, updating..."
    sc.exe config $ServiceName binpath= "`"$InstalledBinary`"" start= auto displayname= "$DisplayName" | Out-Null
} else {
    New-Service `
        -Name $ServiceName `
        -BinaryPathName "`"$InstalledBinary`"" `
        -DisplayName $DisplayName `
        -StartupType Automatic `
        -Description "Marabunta Compute distributed swarm node - participates in the P2P compute mesh" `
        | Out-Null
}

# Set recovery options: restart on 1st failure (60s), 2nd (300s), subsequent (600s).
# Reset failure count after 24 hours (86400 seconds).
sc.exe failure $ServiceName reset= 86400 actions= restart/60000/restart/300000/restart/600000 | Out-Null

# Write config path to registry for the service binary to discover.
$RegPath = "HKLM:\SOFTWARE\MarabuntaCompute\Swarm"
if (-not (Test-Path $RegPath)) {
    New-Item -Path $RegPath -Force | Out-Null
}
Set-ItemProperty -Path $RegPath -Name "ConfigPath" -Value $ConfigPath
Set-ItemProperty -Path $RegPath -Name "DataDir" -Value $DataDir
Set-ItemProperty -Path $RegPath -Name "LogDir" -Value $LogDir

Write-Host "[5/7] Service registered: $ServiceName" -ForegroundColor Green

# -------------------------------------------------------------------------
# 6. Add firewall rules
# -------------------------------------------------------------------------
$FwRuleName = "MarabuntaSwarm"
$ExistingRule = Get-NetFirewallRule -Name $FwRuleName -ErrorAction SilentlyContinue
if (-not $ExistingRule) {
    New-NetFirewallRule `
        -Name $FwRuleName `
        -DisplayName "Marabunta Compute Swarm" `
        -Description "Allow inbound traffic for Marabunta Compute swarm gossip and API" `
        -Direction Inbound `
        -Protocol TCP `
        -LocalPort $ListenPort,$ApiPort `
        -Action Allow `
        -Profile Domain,Private `
        | Out-Null
    Write-Host "[6/7] Firewall rule created: ports $ListenPort, $ApiPort (Domain, Private profiles)" -ForegroundColor Green
} else {
    Write-Host "[6/7] Firewall rule '$FwRuleName' already exists (skipped)" -ForegroundColor Yellow
}

# -------------------------------------------------------------------------
# 7. Start the service
# -------------------------------------------------------------------------
Start-Service -Name $ServiceName
Start-Sleep -Seconds 2
$Svc = Get-Service -Name $ServiceName
Write-Host "[7/7] Service status: $($Svc.Status)" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Installation Complete" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Service Name : $ServiceName"
Write-Host "  Binary       : $InstalledBinary"
Write-Host "  Config       : $ConfigPath"
Write-Host "  Data Dir     : $DataDir"
Write-Host "  Log Dir      : $LogDir"
Write-Host "  Listen Port  : $ListenPort"
Write-Host "  API Port     : $ApiPort"
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Stop service    : Stop-Service $ServiceName"
Write-Host "  Start service   : Start-Service $ServiceName"
Write-Host "  View status     : Get-Service $ServiceName"
Write-Host "  View logs       : Get-Content $LogDir\swarm.log -Tail 50 -Wait"
Write-Host "  Uninstall       : .\uninstall-windows-service.ps1"
Write-Host ""
