#!/bin/bash
# Marabunta - Licensed under the MIT License.
# Marabunta Compute Cluster Setup Script
#
# This script helps initialize and configure a Marabunta Compute cluster.
#
# Usage:
#   ./setup-cluster.sh init                    # Initialize a new cluster
#   ./setup-cluster.sh add-worker MASTER_URL   # Add this node as a worker
#   ./setup-cluster.sh status                  # Show cluster status
#   ./setup-cluster.sh reset                   # Reset local configuration

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}==>${NC} $1"; }

# Configuration
MARABUNTA_CONFIG_DIR="${MARABUNTA_CONFIG_DIR:-/etc/marabunta}"
MARABUNTA_DATA_DIR="${MARABUNTA_DATA_DIR:-/var/lib/marabunta}"
MARABUNTA_LOG_DIR="${MARABUNTA_LOG_DIR:-/var/log/marabunta}"

# Detect OS
detect_os() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    case "$OS" in
        linux)
            if [[ -f /etc/os-release ]]; then
                . /etc/os-release
                DISTRO="$ID"
            fi
            ;;
        darwin)
            DISTRO="macos"
            ;;
    esac
    log_info "Detected OS: $OS ($DISTRO)"
}

# Check if running as root (or with sudo)
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_warn "Not running as root. Some operations may require sudo."
        SUDO="sudo"
    else
        SUDO=""
    fi
}

# Get local IP address
get_local_ip() {
    if [[ "$OS" == "darwin" ]]; then
        ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "127.0.0.1"
    else
        hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 | awk '{print $7}' || echo "127.0.0.1"
    fi
}

# Initialize a new cluster
cmd_init() {
    log_step "Initializing Marabunta Compute cluster..."

    local cluster_name="${1:-marabunta-cluster}"
    local bind_addr="${2:-0.0.0.0}"
    local coordinator_port="${3:-8080}"
    local master_port="${4:-9000}"

    log_info "Cluster name: $cluster_name"
    log_info "Coordinator bind: ${bind_addr}:${coordinator_port}"
    log_info "Master bind: ${bind_addr}:${master_port}"

    # Create directories
    log_step "Creating directories..."
    $SUDO mkdir -p "$MARABUNTA_CONFIG_DIR" "$MARABUNTA_DATA_DIR" "$MARABUNTA_LOG_DIR"

    # Create marabunta user on Linux
    if [[ "$OS" == "linux" ]]; then
        if ! id "marabunta" &>/dev/null; then
            log_step "Creating marabunta user..."
            $SUDO useradd -r -s /bin/false -d "$MARABUNTA_DATA_DIR" -c "Marabunta Compute" marabunta 2>/dev/null || true
        fi
        $SUDO chown -R marabunta:marabunta "$MARABUNTA_DATA_DIR" "$MARABUNTA_LOG_DIR"
    fi

    # Generate cluster configuration
    log_step "Generating configuration..."

    local local_ip=$(get_local_ip)

    # Coordinator config
    cat <<EOF | $SUDO tee "$MARABUNTA_CONFIG_DIR/coordinator.toml" > /dev/null
# Marabunta Compute Coordinator Configuration
# Generated by setup-cluster.sh on $(date)

[server]
bind = "${bind_addr}:${coordinator_port}"
max_connections = 10000

[cluster]
name = "${cluster_name}"
heartbeat_interval = "10s"
node_timeout = "60s"

[storage]
data_dir = "${MARABUNTA_DATA_DIR}/coordinator"

[logging]
level = "info"
format = "json"
file = "${MARABUNTA_LOG_DIR}/coordinator.log"

[metrics]
enabled = true
endpoint = "/metrics"
EOF

    # Master config
    cat <<EOF | $SUDO tee "$MARABUNTA_CONFIG_DIR/master.toml" > /dev/null
# Marabunta Compute Master Configuration
# Generated by setup-cluster.sh on $(date)

[server]
bind = "${bind_addr}:${master_port}"
max_connections = 10000

[coordinator]
url = "http://${local_ip}:${coordinator_port}"

[scheduler]
algorithm = "priority"
queue_size = 100000
max_tasks_per_worker = 10
preemption_enabled = true

[storage]
data_dir = "${MARABUNTA_DATA_DIR}/master"
results_retention = "7d"

[logging]
level = "info"
format = "json"
file = "${MARABUNTA_LOG_DIR}/master.log"

[metrics]
enabled = true
endpoint = "/metrics"
EOF

    # Worker config
    cat <<EOF | $SUDO tee "$MARABUNTA_CONFIG_DIR/worker.toml" > /dev/null
# Marabunta Compute Worker Configuration
# Generated by setup-cluster.sh on $(date)

[master]
url = "http://${local_ip}:${master_port}"

[coordinator]
url = "http://${local_ip}:${coordinator_port}"

[worker]
cores = 0
heartbeat_interval = "10s"

[execution]
timeout = "1h"
temp_dir = "${MARABUNTA_DATA_DIR}/tmp"
checkpoint_interval = "5m"

[storage]
data_dir = "${MARABUNTA_DATA_DIR}/worker"
checkpoint_dir = "${MARABUNTA_DATA_DIR}/checkpoints"

[logging]
level = "info"
format = "json"
file = "${MARABUNTA_LOG_DIR}/worker.log"
EOF

    # Create data subdirectories
    $SUDO mkdir -p "$MARABUNTA_DATA_DIR/coordinator" "$MARABUNTA_DATA_DIR/master" "$MARABUNTA_DATA_DIR/worker" "$MARABUNTA_DATA_DIR/tmp" "$MARABUNTA_DATA_DIR/checkpoints"

    if [[ "$OS" == "linux" ]]; then
        $SUDO chown -R marabunta:marabunta "$MARABUNTA_DATA_DIR"
    fi

    echo ""
    log_info "Cluster initialized successfully!"
    echo ""
    echo "Configuration files created in: $MARABUNTA_CONFIG_DIR"
    echo ""
    echo "To start the cluster:"

    if [[ "$OS" == "linux" ]] && command -v systemctl &> /dev/null; then
        echo "  sudo systemctl start marabunta-coordinator"
        echo "  sudo systemctl start marabunta-master"
        echo "  sudo systemctl start marabunta-worker"
    else
        echo "  marabunta-coordinator --config $MARABUNTA_CONFIG_DIR/coordinator.toml"
        echo "  marabunta-master --config $MARABUNTA_CONFIG_DIR/master.toml"
        echo "  marabunta-worker --config $MARABUNTA_CONFIG_DIR/worker.toml"
    fi
    echo ""
    echo "Coordinator URL: http://${local_ip}:${coordinator_port}"
    echo "Master URL: http://${local_ip}:${master_port}"
}

# Add this node as a worker to an existing cluster
cmd_add_worker() {
    local master_url="$1"
    local coordinator_url="${2:-}"

    if [[ -z "$master_url" ]]; then
        log_error "Master URL required"
        echo "Usage: $0 add-worker MASTER_URL [COORDIGLOBAL_ALLIANCE_T1R_URL]"
        exit 1
    fi

    log_step "Configuring this node as a worker..."
    log_info "Master URL: $master_url"

    # Extract coordinator URL from master if not provided
    if [[ -z "$coordinator_url" ]]; then
        coordinator_url="${master_url%:*}:8080"
        log_info "Coordinator URL (inferred): $coordinator_url"
    fi

    # Create directories
    $SUDO mkdir -p "$MARABUNTA_CONFIG_DIR" "$MARABUNTA_DATA_DIR" "$MARABUNTA_LOG_DIR"

    # Create marabunta user on Linux
    if [[ "$OS" == "linux" ]]; then
        if ! id "marabunta" &>/dev/null; then
            $SUDO useradd -r -s /bin/false -d "$MARABUNTA_DATA_DIR" -c "Marabunta Compute" marabunta 2>/dev/null || true
        fi
        $SUDO chown -R marabunta:marabunta "$MARABUNTA_DATA_DIR" "$MARABUNTA_LOG_DIR"
    fi

    # Generate worker configuration
    cat <<EOF | $SUDO tee "$MARABUNTA_CONFIG_DIR/worker.toml" > /dev/null
# Marabunta Compute Worker Configuration
# Generated by setup-cluster.sh on $(date)

[master]
url = "${master_url}"

[coordinator]
url = "${coordinator_url}"

[worker]
cores = 0
heartbeat_interval = "10s"

[execution]
timeout = "1h"
temp_dir = "${MARABUNTA_DATA_DIR}/tmp"
checkpoint_interval = "5m"

[storage]
data_dir = "${MARABUNTA_DATA_DIR}/worker"
checkpoint_dir = "${MARABUNTA_DATA_DIR}/checkpoints"

[logging]
level = "info"
format = "json"
file = "${MARABUNTA_LOG_DIR}/worker.log"
EOF

    $SUDO mkdir -p "$MARABUNTA_DATA_DIR/worker" "$MARABUNTA_DATA_DIR/tmp" "$MARABUNTA_DATA_DIR/checkpoints"

    if [[ "$OS" == "linux" ]]; then
        $SUDO chown -R marabunta:marabunta "$MARABUNTA_DATA_DIR"
    fi

    echo ""
    log_info "Worker configured successfully!"
    echo ""
    echo "To start the worker:"

    if [[ "$OS" == "linux" ]] && command -v systemctl &> /dev/null; then
        echo "  sudo systemctl start marabunta-worker"
        echo "  sudo systemctl enable marabunta-worker  # Enable on boot"
    else
        echo "  marabunta-worker --config $MARABUNTA_CONFIG_DIR/worker.toml"
    fi
}

# Show cluster status
cmd_status() {
    log_step "Checking cluster status..."

    local coordinator_url=""
    local master_url=""

    # Try to read from config
    if [[ -f "$MARABUNTA_CONFIG_DIR/coordinator.toml" ]]; then
        coordinator_url=$(grep -E "^url\s*=" "$MARABUNTA_CONFIG_DIR/master.toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\(.*\)"/\1/' || echo "")
    fi

    if [[ -f "$MARABUNTA_CONFIG_DIR/worker.toml" ]]; then
        master_url=$(grep -E "^url\s*=" "$MARABUNTA_CONFIG_DIR/worker.toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\(.*\)"/\1/' || echo "")
    fi

    # Use CLI if available
    if command -v marabunta &> /dev/null; then
        marabunta status
    else
        echo ""
        echo "Configuration directory: $MARABUNTA_CONFIG_DIR"
        echo ""

        # Check services on Linux
        if [[ "$OS" == "linux" ]] && command -v systemctl &> /dev/null; then
            echo "Service status:"
            for service in marabunta-coordinator marabunta-master marabunta-worker; do
                if systemctl is-active --quiet "$service" 2>/dev/null; then
                    echo -e "  $service: ${GREEN}running${NC}"
                else
                    echo -e "  $service: ${RED}stopped${NC}"
                fi
            done
        fi

        echo ""
        echo "Use 'marabunta status' for detailed cluster information"
    fi
}

# Reset local configuration
cmd_reset() {
    log_warn "This will remove all local Marabunta Compute configuration and data!"
    read -p "Are you sure? (y/N) " -n 1 -r
    echo

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Aborted"
        exit 0
    fi

    log_step "Stopping services..."
    if [[ "$OS" == "linux" ]] && command -v systemctl &> /dev/null; then
        $SUDO systemctl stop marabunta-coordinator marabunta-master marabunta-worker 2>/dev/null || true
    fi

    log_step "Removing configuration..."
    $SUDO rm -rf "$MARABUNTA_CONFIG_DIR"/*

    log_step "Removing data..."
    $SUDO rm -rf "$MARABUNTA_DATA_DIR"/*

    log_step "Removing logs..."
    $SUDO rm -rf "$MARABUNTA_LOG_DIR"/*

    log_info "Reset complete"
}

# Show help
cmd_help() {
    echo "Marabunta Compute Cluster Setup Script"
    echo ""
    echo "Usage: $0 COMMAND [OPTIONS]"
    echo ""
    echo "Commands:"
    echo "  init [NAME] [BIND] [COORD_PORT] [MASTER_PORT]"
    echo "                          Initialize a new cluster"
    echo "  add-worker MASTER_URL [COORDIGLOBAL_ALLIANCE_T1R_URL]"
    echo "                          Add this node as a worker"
    echo "  status                  Show cluster status"
    echo "  reset                   Reset local configuration"
    echo "  help                    Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 init                 # Initialize with defaults"
    echo "  $0 init my-cluster      # Initialize with custom name"
    echo "  $0 add-worker http://master.example.com:9000"
    echo ""
    echo "Environment variables:"
    echo "  MARABUNTA_CONFIG_DIR         Configuration directory (default: /etc/marabunta)"
    echo "  MARABUNTA_DATA_DIR           Data directory (default: /var/lib/marabunta)"
    echo "  MARABUNTA_LOG_DIR            Log directory (default: /var/log/marabunta)"
}

# Main
main() {
    detect_os
    check_root

    local cmd="${1:-help}"
    shift || true

    case "$cmd" in
        init)
            cmd_init "$@"
            ;;
        add-worker|add_worker|worker)
            cmd_add_worker "$@"
            ;;
        status)
            cmd_status "$@"
            ;;
        reset)
            cmd_reset "$@"
            ;;
        help|--help|-h)
            cmd_help
            ;;
        *)
            log_error "Unknown command: $cmd"
            cmd_help
            exit 1
            ;;
    esac
}

main "$@"
